const ingredientsData = {
    initial: [
        { name: '쌀', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Frice.png?alt=media&token=49a02d4f-1248-4e34-8785-4089c6298357', cleaning: '미지근한 물에 30분 이상 불린 후 깨끗이 씻어요.', cubing: '불린 쌀을 갈아서 쌀가루로 만들거나, 밥을 지어 으깨서 큐브에 담아 얼려요.', pairing: '소고기, 애호박, 브로콜리', notes: '초기 이유식의 기본! 알레르기 반응이 거의 없어요.' },
        { name: '찹쌀', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fglutinous-rice.png?alt=media&token=5c85bca3-4a1e-4ce9-8422-b52f6f4d8958', cleaning: '깨끗이 씻어 1시간 정도 충분히 불려주세요.', cubing: '불린 찹쌀을 갈아 가루로 만들거나 죽을 쑤어 소분해요.', pairing: '닭고기, 무, 단호박', notes: '소화가 잘 되고 성질이 따뜻해 초기 식재료로 좋아요.' },
        { name: '소고기(안심)', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fbeef.png?alt=media&token=875a6c42-7369-424a-9549-a363765123d8', cleaning: '찬물에 30분 정도 담가 핏물을 빼고 지방을 제거해요.', cubing: '삶아서 곱게 다지거나 믹서에 간 후 육수와 함께 얼려요.', pairing: '브로콜리, 청경채, 비타민', notes: '6개월 이후 아기에게 필수적인 철분 공급원입니다.' },
        { name: '브로콜리', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fbroccoli.png?alt=media&token=8d27a499-d6e4-4423-8a3b-a2c676239f1c', cleaning: '식초물에 담가 꽃송이 사이 불순물을 제거해요.', cubing: '꽃부분만 데쳐서 곱게 다져 큐브에 담아요.', pairing: '소고기, 고구마, 양파', notes: '비타민 C가 풍부하며 줄기는 소화가 어려우니 꽃부분만 써요.' },
        { name: '애호박', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fzucchini.png?alt=media&token=c2a67e9f-a4f6-4038-922e-a589b3f3e1a7', cleaning: '껍질을 씻고 양 끝을 잘라내요.', cubing: '껍질과 씨를 제거하고 데친 후 갈아서 얼려요.', pairing: '쌀, 소고기, 닭고기', notes: '소화가 잘 되고 맛이 순해 초기 채소로 적합해요.' }
    ],
    mid: [
        { name: '닭고기(가슴살)', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fchicken.png?alt=media&token=0a3a7f83-c20e-473d-82a1-1b9131c93a02', cleaning: '기름기와 힘줄을 제거하고 우유나 분유물에 담가 잡내를 빼요.', cubing: '삶아서 잘게 다지거나 믹서에 갈아 육수와 함께 얼려요.', pairing: '당근, 시금치, 표고버섯', notes: '소고기 다음으로 중요한 단백질원입니다.' },
        { name: '계란노른자', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fegg-yolk.png?alt=media&token=c1a3a4a1-4a11-4475-9c2e-48a0d9b4343d', cleaning: '완숙으로 삶아요.', cubing: '노른자만 분리해 체에 내리거나 으깨서 얼려요.', pairing: '소고기, 브로콜리, 감자', notes: '알레르기 반응을 확인하며 소량씩 시작하세요.' },
        { name: '대구살', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fcod.png?alt=media&token=4453b6f0-4a82-4a0b-9c29-4d7a8d38058a', cleaning: '가시가 없는지 확인하고 씻어요.', cubing: '쪄서 살만 발라 으깨서 얼려요.', pairing: '애호박, 무, 쑥갓', notes: '흰살생선은 지방이 적고 담백해 소화가 잘 돼요.' }
    ],
    late: [
        { name: '돼지고기(안심)', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fpork.png?alt=media&token=963b5f01-723a-4171-8557-4b77f8842247', cleaning: '기름기를 제거하고 찬물에 담가 핏물을 빼요.', cubing: '삶아서 5~7mm 크기로 다져서 얼려요.', pairing: '양파, 사과, 버섯', notes: '기름기 없는 안심 부위부터 시작하세요.' },
        { name: '아기치즈', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fcheese.png?alt=media&token=7a9e3a62-4b23-45d6-8848-4a946f0e27c1', cleaning: '-', cubing: '작게 자르거나 찢어서 소분해요.', pairing: '단호박, 브로콜리, 고구마', notes: '나트륨이 적은 1단계 아기 전용 치즈를 쓰세요.' },
        { name: '새우(생물)', img: 'https://firebasestorage.googleapis.com/v0/b/mamma-calculator.appspot.com/o/illustrations%2Fshrimp.png?alt=media&token=5a576a11-4a57-4a0d-9b4e-4e4a7a8a7a8a', cleaning: '머리, 껍질, 내장을 제거하고 소금물에 씻어요.', cubing: '데쳐서 7mm 크기로 다져서 얼려요.', pairing: '파프리카, 양파, 계란', notes: '풍미가 좋아 아기들이 매우 좋아하는 식재료예요.' }
    ]
}